services:
  postgres:
    image: postgres
    container_name: decoder-authentication
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: decoder-authentication

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
