spring:
  application:
    name: decoder-authentication
  datasource:
    url: jdbc:postgresql://localhost:5431/decoder-authentication
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always

server:
  port: 8087

logging:
  level:
    com.delon.decoderauthentication: trace
    org.hibernate: info
    root: info
    web: debug
